---
- name: Install the nginx rpm from a remote repo
  yum:
    name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    state: present

- name: Install Nginx Service
  yum: name=nginx state=latest update_cache=true

- name: Update Nginx Configuration
  template: src=../templates/nginx.conf dest=/etc/nginx/conf.d/default.conf

- name: Restart the Nginx service
  service: name=nginx state=restarted enabled=true

